# Generated by Django 4.1.4 on 2022-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ManyToManyField(related_name='user_type', to='api.usertype'),
        ),
    ]
